### ISSUE TITLE
thread handling during lastz alignment

### ISSUE THREAD

**Issue by kriemo** [slncky/slncky#1]
Thanks for developing such a useful tool. I noticed that when using `slncky` that the number of threads used during the `lastz` alignment is not equal to the number of threads specified using `-n`.  For example, when setting `-n 4`, lastz runs on 20-30 threads. This can be problematic when running `slncky` on a shared cluster. Is it possible to limit the number of threads used by slncky? Thanks!

**Comment by jjenny** [comment]
Hi Kriemo,

Thanks for the kind words.  I'm testing an updated version right now that completely limits the number of threads to 1.  However, it is quite slow.  How many transcripts are in your input file? If you have to work with 1 thread, we may have to brainstorm other ideas for running slncky.  Alternatively, many shared clusters allow multithreaded software if you specify certain flags. Do you know what type of cluster you have?  

I will ping you when I've updated slncky on github.

-Jenny

**Comment by kriemo** [comment]
Thanks for the quick response. For my input files I've been working with ~1,000 - 10,000 transcripts. 

I'm working on an LSF/drmaa cluster, and I can allocate multiple threads for running slncky. When I've run slncky with `-n  4` I get up to 30 threads during the lastz alignments. As a workaround I can reserve 30 cores for the job on the cluster to avoid consuming unallocated cores.

**Comment by jjenny** [comment]
Hi kriemo,

You can run multiple threads on a single core so you don't have to reserve 30 cores.  The important thing is to tell LSF/drmaa to keep all the threads on the same core.  I know for LSF the argument for this is span[hosts=1] but I don't know what it is for LSF/drmaa.  

If your input file is between 1,000 - 10,000 then I highly recommend running slncky with the multithreaded option.  I am running a test with -n=1 on a set of ~2000 transcripts and it's taking >12 hours (still going, will update code when the test finishes)!

-Jenny

**Comment by jjenny** [comment]
Hi kriemo,

I've updated the code so that -n 1 limits all threads to exactly 1.  You can pull it form the github.  As I mentioned though, it will run quite slowly.  If you are not able to specify a single host and run slncky multithreaded, I would suggest breaking up files into smaller files of transcripts and running them on the cluster in parallel.

**Comment by kriemo** [comment]
Thanks for incorporating this option and for the advice.
