### ISSUE TITLE
bed file

### ISSUE THREAD

**Issue by kevin199011** [slncky/slncky#2]
Hi, I'm new to this and have question about the bed file for the input of slncky.
I have transcripts.gtf generated by stringTie. I'm wondering how can I convert this to a proper bed file for slncky? Thank you a lot!

Kevin

**Comment by jjenny** [comment]
Hey Kevin,

You can use this script to convert: https://gist.github.com/jjenny/6148951

Note that the gtf2bed.py script uses python3 whereas slncky uses python2!

**Comment by kevin199011** [comment]
Many thanks!
