### ISSUE TITLE
Broken link for annotations.tar.gz

### ISSUE THREAD

**Issue by khourhin** [slncky/slncky#4]
Hi,

The link for the annotation files:

https://www.dropbox.com/s/pq7wsjx61sp8ghm/annotations.tar.gz?dl=0

Found at:

https://slncky.github.io/install.html

is apparently broken.

**Comment by jjenny** [comment]
The link has now been updated to: 

https://www.dropbox.com/s/jifnrr3kjq95w64/annotations.tar.gz?dl=0
